name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Server Info
        shell: powershell
        run: |
          Write-Host "===== GitHub Runner Connected ====="
          hostname
          pwd
          node -v
          npm -v
          git --version