name: Git Pull

on:
  push:
    branches:
      - main

jobs:
  pull:
    runs-on: self-hosted

    defaults:
      run:
        shell: powershell

    steps:
      - name: Update Repository
        run: |
          Set-Location "C:\Users\Fetra\Documents\Fetsu\ProjectWebAnt"

          git fetch origin
          git reset --hard origin/main
          git clean -fd

          git status